lint:
  template_strings:
    - input.template.json
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nucleovar_logo_light.png
    - docs/images/nf-core-nucleovar_logo_light.png
    - docs/images/nf-core-nucleovar_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes.config
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nucleovar_logo_light.png
    - docs/images/nf-core-nucleovar_logo_light.png
    - docs/images/nf-core-nucleovar_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .prettierignore
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - .github/CONTRIBUTING.md
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - process.cpus
    - process.memory
    - process.time
    - custom_config
repository_type: pipeline
template:
  prefix: msk
  skip:
    - igenomes
    - nf_core_configs
